# Generated by Django 5.0 on 2024-01-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairmanapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairman',
            name='pic',
            field=models.FileField(default='monkey.jpg', upload_to='media/images/'),
        ),
    ]
